manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: dhruvinsh
      url-base: https://github.com/dhruvinsh
    - name: local
      url-base: /Users/jeff/ws/zmk-config
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-tri-state
      remote: dhruvinsh
      revision: main
    - name: regret-shield
      remote: local
      revision: main
      path: modules/regret-shield
  self:
    path: config
